name: Backup GitHub Repositories
on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  backup:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash
          sudo apt install crystal
          curl https://rclone.org/install.sh | sudo bash
          crystal --version
          rclone --version
      - uses: actions/checkout@v2
      - name: Backup
        env: # Or as an environment variable
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: crystal run main.cr
