name: Backup GitHub Repositories
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  backup:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash
          curl https://rclone.org/install.sh | sudo bash
      - uses: actions/checkout@v2
      - name: Backup
        env: # Or as an environment variable
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: crystal run main.cr
